### ISSUE TITLE
Initialization fails following motion correction

### ISSUE THREAD

**Issue by willyh101** [willyh101/live2p#2]
New issue, might be related to caiman update. Appears to only be an issue on recent installs of live2p. Live2p raises `OSError: Unable to synchronously create file (unable to truncate a file which is already open)` while trying to save a h5df file with the same name (each plane is getting the same file name and therefore fails) for OnACID processing, but Caiman should be able to read the mmap directly.

We should try to disable saving in params or see what is causing the intermediate h5df file to be saved- since there is already a mmap file, it's unclear why a h5 is also being written to disk.

Verbose output from live2p:
```
(live2p_masashi) C:\Users\scanimage\live2p>live2p -d 2


    Welcome to live2p (v0.3)!

* Realtime, multiplane motion correction and source extraction using CaImAn OnACID, ScanImage, and websockets.

* A popup GUI will ask you to select you seed image by default.
* The seed image should be ~500 frames and will take ~ 30 seconds to process before you start the experiment.

Loading...


[INFO] Starting server...
[INFO] HOST=localhost
[INFO] PORT=6000
[INFO] Live2p websocket server ready!
[INFO] Connected to client 127.0.0.1
[INFO] Recieved setup data from SI
[INFO] nchannels set to 2
[INFO] nplanes set to 3
[INFO] fr set to 7.518024691358023
[INFO] folder set to F:\live2p_temp\New
[INFO] Starting RealTimeWorker 0
00015922 - DEBUG    - [workers:__init__:44] - Setting up params...
[INFO] Starting RealTimeWorker 1
00015922 - DEBUG    - [workers:__init__:44] - Setting up params...
[INFO] Starting RealTimeWorker 2
00015922 - DEBUG    - [workers:__init__:44] - Setting up params...
00015969 - DEBUG    - [workers:_setup_folders:115] - Set temp_path to F:\live2p_temp\live2p\tmp
00015969 - DEBUG    - [workers:_setup_folders:115] - Set temp_path to F:\live2p_temp\live2p\tmp
00015969 - DEBUG    - [workers:_setup_folders:118] - Set out_path to F:\live2p_temp\live2p\out
00015969 - DEBUG    - [workers:_setup_folders:118] - Set out_path to F:\live2p_temp\live2p\out
00015969 - DEBUG    - [workers:_setup_folders:122] - Set working dir to F:\live2p_temp\live2p\tmp
00015969 - DEBUG    - [workers:_setup_folders:122] - Set working dir to F:\live2p_temp\live2p\tmp
00015969 - DEBUG    - [workers:__init__:180] - Max frames set to 128000
00015969 - DEBUG    - [workers:__init__:180] - Max frames set to 128000
Plane 2: Found 2 sources from MM3D...
00016000 - INFO     - [workers:__init__:216] - Starting live2p worker.
Plane 0: Found 6 sources from MM3D...
00016000 - INFO     - [workers:__init__:216] - Starting live2p worker.
00016000 - INFO     - [workers:initialize_onacid:234] - Starting new OnACID initialization for live2p.
00016000 - DEBUG    - [workers:make_init_mmap:239] - Making init memmap...
00016000 - INFO     - [workers:initialize_onacid:234] - Starting new OnACID initialization for live2p.
00016000 - DEBUG    - [workers:make_init_mmap:239] - Making init memmap...
00016086 - DEBUG    - [workers:_setup_folders:115] - Set temp_path to F:\live2p_temp\live2p\tmp
00016086 - DEBUG    - [workers:_setup_folders:118] - Set out_path to F:\live2p_temp\live2p\out
00016086 - DEBUG    - [workers:_setup_folders:122] - Set working dir to F:\live2p_temp\live2p\tmp
00016086 - DEBUG    - [workers:__init__:180] - Max frames set to 128000
Plane 1: Found 8 sources from MM3D...
00016101 - INFO     - [workers:__init__:216] - Starting live2p worker.
00016101 - INFO     - [workers:initialize_onacid:234] - Starting new OnACID initialization for live2p.
00016101 - DEBUG    - [workers:make_init_mmap:239] - Making init memmap...
00018429 - DEBUG    - [workers:make_init_mmap:257] - Init mmap saved to initplane0_d1_412_d2_412_d3_1_order_C_frames_500.mmap.
00018632 - DEBUG    - [workers:make_init_mmap:257] - Init mmap saved to initplane2_d1_412_d2_412_d3_1_order_C_frames_500.mmap.
00018898 - ERROR    - [server:handler:238] - connection handler failed
Traceback (most recent call last):
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\websockets\legacy\server.py", line 1175, in _ws_handler
    return await cast(
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 131, in handle_incoming_ws
    await self.route(payload)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 182, in route
    await self.handle_setup(data)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 238, in handle_setup
    self.workers = await asyncio.gather(*tasks)
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 273, in start_worker
    worker = RealTimeQueue(self.init_files, plane, self.nchannels, self.nplanes,
  File "c:\users\scanimage\live2p\live2p\workers.py", line 220, in __init__
    self.initialize_onacid()
  File "c:\users\scanimage\live2p\live2p\workers.py", line 236, in initialize_onacid
    self.acid = self._initialize_new(init_mmap)
  File "c:\users\scanimage\live2p\live2p\utils.py", line 219, in wrapper_timer
    value = func(*args, **kwargs)
  File "c:\users\scanimage\live2p\live2p\workers.py", line 282, in _initialize_new
    acid.initialize_online(T=self.num_frames_max)
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py", line 960, in initialize_online
    mc = caiman.motion_correction.MotionCorrect(Y, dview=self.dview, **self.params.get_group('motion'))
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\caiman\motion_correction.py", line 178, in __init__
    cm.movie(fname).save('tmp_mov_mot_corr.hdf5')
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\caiman\base\timeseries.py", line 276, in save    with h5py.File(file_name, "w") as f:
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\h5py\_hl\files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\scanimage\anaconda3\envs\live2p_masashi\lib\site-packages\h5py\_hl\files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 126, in h5py.h5f.create
OSError: Unable to synchronously create file (unable to truncate a file which is already open)
00019085 - DEBUG    - [workers:make_init_mmap:257] - Init mmap saved to initplane1_d1_412_d2_412_d3_1_order_C_frames_500.mmap.
```

**Comment by willyh101** [comment]
via Masashi:

As you recommended, I used miniforge to re-install live2p and related packages with your yaml file in our scanimage PC.
Then, we got a new error message, as you can see in the attached.

Caiman tried to reshape 84872000 data into 210944 x 500, then it caused an error, due to size mismatch, during the seed initialization step.
Our x-y “Cut off” parameters in rig file and make mask 3d file is x:412, y:412 pixel, and we feed 500 frames for the initialization of caiman.
So, it seems that caiman tried to reshape the (412 x 412) x 500 data points (84872000 data points) into (412 x 512) x 500 data points (210944 x 500).

Do you know if we need to specify “cut-off” parameters within caiman files somewhere, in addition to rig file and make mask 3d file?
I assume that “cut off“ parameters are mismatched between rig file and caiman.

```
(live2p) C:\Users\scanimage>live2p -d 2


    Welcome to live2p (v0.3)!

* Realtime, multiplane motion correction and source extraction using CaImAn OnACID, ScanImage, and websockets.

* A popup GUI will ask you to select you seed image by default.
* The seed image should be ~500 frames and will take ~ 30 seconds to process before you start the experiment.

Loading...


[INFO] Starting server...
[INFO] HOST=localhost
[INFO] PORT=5003
[INFO] Live2p websocket server ready!
[INFO] Connected to client 127.0.0.1
[INFO] Recieved setup data from SI
[INFO] nchannels set to 2
[INFO] nplanes set to 3
[INFO] fr set to 7.518024691358023
[INFO] folder set to F:\Data\Masashi\B24-1\Live2P_1
[INFO] Starting RealTimeWorker 0
00021591 - DEBUG    - [workers:__init__:44] - Setting up params...
[INFO] Starting RealTimeWorker 1[INFO] Starting RealTimeWorker 2

00021593 - DEBUG    - [workers:__init__:44] - Setting up params...
00021593 - DEBUG    - [workers:__init__:44] - Setting up params...
00021624 - DEBUG    - [workers:_setup_folders:115] - Set temp_path to F:\Data\Masashi\B24-1\Live2P_1\live2p\tmp
00021624 - DEBUG    - [workers:_setup_folders:118] - Set out_path to F:\Data\Masashi\B24-1\Live2P_1\live2p\out
00021624 - DEBUG    - [workers:_setup_folders:122] - Set working dir to F:\Data\Masashi\B24-1\Live2P_1\live2p\tmp
00021624 - DEBUG    - [workers:__init__:180] - Max frames set to 128000
00021624 - DEBUG    - [workers:_setup_folders:115] - Set temp_path to F:\Data\Masashi\B24-1\Live2P_1\live2p\tmp
00021624 - DEBUG    - [workers:_setup_folders:115] - Set temp_path to F:\Data\Masashi\B24-1\Live2P_1\live2p\tmp
00021625 - DEBUG    - [workers:_setup_folders:118] - Set out_path to F:\Data\Masashi\B24-1\Live2P_1\live2p\out
00021625 - DEBUG    - [workers:_setup_folders:122] - Set working dir to F:\Data\Masashi\B24-1\Live2P_1\live2p\tmp
00021625 - DEBUG    - [workers:_setup_folders:118] - Set out_path to F:\Data\Masashi\B24-1\Live2P_1\live2p\out
00021625 - DEBUG    - [workers:__init__:180] - Max frames set to 128000
00021625 - DEBUG    - [workers:_setup_folders:122] - Set working dir to F:\Data\Masashi\B24-1\Live2P_1\live2p\tmp
00021625 - DEBUG    - [workers:__init__:180] - Max frames set to 128000
Plane 2: Found 96 sources from MM3D...
00022060 - INFO     - [workers:__init__:216] - Starting live2p worker.
Plane 0: Found 96 sources from MM3D...
00022060 - INFO     - [workers:initialize_onacid:234] - Starting new OnACID initialization for live2p.
00022063 - INFO     - [workers:__init__:216] - Starting live2p worker.
00022063 - DEBUG    - [workers:make_init_mmap:239] - Making init memmap...
00022064 - INFO     - [workers:initialize_onacid:234] - Starting new OnACID initialization for live2p.
00022064 - DEBUG    - [workers:make_init_mmap:239] - Making init memmap...
Plane 1: Found 96 sources from MM3D...
00022072 - INFO     - [workers:__init__:216] - Starting live2p worker.
00022072 - INFO     - [workers:initialize_onacid:234] - Starting new OnACID initialization for live2p.
00022072 - DEBUG    - [workers:make_init_mmap:239] - Making init memmap...
00024647 - DEBUG    - [workers:make_init_mmap:257] - Init mmap saved to initplane2_d1_412_d2_412_d3_1_order_C_frames_500_.mmap.
00024669 - DEBUG    - [workers:make_init_mmap:257] - Init mmap saved to initplane1_d1_412_d2_412_d3_1_order_C_frames_500_.mmap.
00024715 - DEBUG    - [workers:make_init_mmap:257] - Init mmap saved to initplane0_d1_412_d2_412_d3_1_order_C_frames_500_.mmap.
00042728 - ERROR    - [server:handler:295] - Error in connection handler
Traceback (most recent call last):
  File "C:\Users\scanimage\miniforge3\envs\live2p\lib\site-packages\websockets\legacy\server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 130, in handle_incoming_ws
    await self.route(payload)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 181, in route
    await self.handle_setup(data)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 237, in handle_setup
    self.workers = await asyncio.gather(*tasks)
  File "C:\Users\scanimage\miniforge3\envs\live2p\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\scanimage\live2p\live2p\websockets\server.py", line 273, in start_worker
    self.params, self.qs[plane], Ain_path=self.Ain_path, **self.kwargs)
  File "c:\users\scanimage\live2p\live2p\workers.py", line 220, in __init__
    self.initialize_onacid()
  File "c:\users\scanimage\live2p\live2p\workers.py", line 236, in initialize_onacid
    self.acid = self._initialize_new(init_mmap)
  File "c:\users\scanimage\live2p\live2p\utils.py", line 219, in wrapper_timer
    value = func(*args, **kwargs)
  File "c:\users\scanimage\live2p\live2p\workers.py", line 282, in _initialize_new
    acid.initialize_online(T=self.num_frames_max)
  File "C:\Users\scanimage\miniforge3\envs\live2p\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py", line 1032, in initialize_online
    gSig=self.params.get('init', 'gSig'), return_object=False)
  File "C:\Users\scanimage\miniforge3\envs\live2p\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py", line 1532, in seeded_initialization
    Yr = np.reshape(Y, (Ain.shape[0], Y.shape[-1]), order='F')
  File "<__array_function__ internals>", line 6, in reshape
  File "C:\Users\scanimage\miniforge3\envs\live2p\lib\site-packages\numpy\core\fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\scanimage\miniforge3\envs\live2p\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 84872000 into shape (210944,500)
```

**Comment by willyh101** [comment]
Added a hotfix [027ac89](https://github.com/willyh101/live2p/commit/027ac89a1b26321f46fdfbdfcf6f06f392dc50a5) for addition cli debugging. Please re-pull the repo and send me the output of `live2p -d 2`.

**Comment by mh1668** [comment]
Hi Will,
Thank you very much for your help.

1) I updated the live2p packages using, "pip install -e ."
2) I put the same Y-Cropping value that you use.

Now, live2p seems to work properly, although I am not sure if all live2p functions work perfectly.
At the end of the session, I got the data.mat and other python file.
The following is the copy of the window of the miniforge prompt running live2p:

[Live2P_DebugMode2_20240205.txt](https://github.com/willyh101/live2p/files/14174327/Live2P_DebugMode2_20240205.txt)

**Comment by willyh101** [comment]
Glad it's working. Yes, those are the final output files.

Be 100% sure the **dimensions in your makeMasks3D script match what you put into live2p**, otherwise you will have very weird errors pop up. They can be hard to diagnose. I'm not sure what the exact cause of the original error was, but if it happens again (or you have a new problem) please create another issue here with as much information as you can provide and I'll help you sort it out.

For now, I'll close this issue as it's seemingly fixed itself...

**Comment by mh1668** [comment]
>>Yes, those are the final output files.
OK, I got it. It is nice that live2p is working properly now.

>>Be 100% sure the dimensions in your makeMasks3D script match what you put into live2p
I will check the makeMask3D script and rig file again, just in case.
Thanks again for your kind help!

Masashi
